@ECHO OFF

REM *****************************************************************
REM
REM THIS AUTOEXEC.BAT FILE SHOULD NOT BE CHANGED.  IF IT IS NECESSARY
REM TO HAVE CERTAIN PROGRAMS RUN AT "BOOT TIME", THEN PLACE THEM IN
REM THE \ETC\STARTUP\USERDEF.BAT.  SEE THE STARTUP AND USERDEF MANUAL
REM PAGES FOR MORE INFORMATION.
REM
REM Copyright 1992 Paul Walters
REM *****************************************************************

PATH=C:\BIN;C:\USR\DOS;C:\USR\BIN;
SET COMSPEC=C:\USR\DOS\COMMAND.COM
SET TEMP=C:\TMP
:LOOP
\BIN\LOGIN
GOTO LOOP
